--1. Bảng HOCKY
CREATE TABLE HOCKY (
    MaHK        VARCHAR2(12 CHAR) NOT NULL,
    HocKy       VARCHAR2(15 CHAR),
    NamHoc      VARCHAR2(12 CHAR),
    CONSTRAINT PK_HOCKY PRIMARY KEY (MaHK)
);

--2. Bảng CHUCVU
CREATE TABLE CHUCVU (
    MaCV    VARCHAR2(10 BYTE) NOT NULL,
    TenCV   VARCHAR2(100 CHAR),
    CONSTRAINT PK_CHUCVU PRIMARY KEY (MaCV)
);

--3. Bảng GIAOVIEN
CREATE TABLE GIAOVIEN (
    MaGV            VARCHAR2(10 BYTE) NOT NULL,
    HoGV            VARCHAR2(30 CHAR) NOT NULL,
    TenGV           VARCHAR2(15 CHAR) NOT NULL,
    GioiTinh        VARCHAR2(5 CHAR),
    ChuyenMon       VARCHAR2(200 CHAR),
    MaTCM           VARCHAR2(10 BYTE), -- Sẽ thêm FK sau khi TOCHUYENMON được tạo
    SoTietQuyDinh   NUMBER,
    SoTietThucHien  NUMBER,
    SoTietDuThieu   NUMBER,
    Email           VARCHAR2(100 BYTE),
    SDT             VARCHAR2(15 BYTE),
    MatKhau         VARCHAR2(100 BYTE),
    GhiChu          VARCHAR2(200 CHAR),
    CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MaGV)
);

--4. Bảng TOCHUYENMON (Tham chiếu đến GIAOVIEN đã tạo cho ToTruong, ToPho)
CREATE TABLE TOCHUYENMON (
    MaTCM       VARCHAR2(10 BYTE) NOT NULL,
    TenTCM      VARCHAR2(100 CHAR),
    ToTruong    VARCHAR2(10 BYTE),
    ToPho       VARCHAR2(10 BYTE),
    CONSTRAINT PK_TOCHUYENMON PRIMARY KEY (MaTCM),
    CONSTRAINT FK_TOCHUYENMON_ToTruong FOREIGN KEY (ToTruong) REFERENCES GIAOVIEN(MaGV),
    CONSTRAINT FK_TOCHUYENMON_ToPho FOREIGN KEY (ToPho) REFERENCES GIAOVIEN(MaGV)
);

-- Thêm Khóa ngoại từ GIAOVIEN đến TOCHUYENMON (sau khi cả hai bảng đã được tạo)
ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN_TOCHUYENMON FOREIGN KEY (MaTCM) REFERENCES TOCHUYENMON(MaTCM);

--5. Bảng MONHOC
CREATE TABLE MONHOC (
    MaMH    VARCHAR2(10 BYTE) NOT NULL,
    TenMH   VARCHAR2(100 CHAR),
    Khoi    VARCHAR2(5 CHAR),
    MaTCM   VARCHAR2(10 BYTE),
    CONSTRAINT PK_MONHOC PRIMARY KEY (MaMH),
    CONSTRAINT FK_MONHOC_TOCHUYENMON FOREIGN KEY (MaTCM) REFERENCES TOCHUYENMON(MaTCM)
);

--6. Bảng LOP
CREATE TABLE LOP (
    MaLop   VARCHAR2(10 BYTE) NOT NULL,
    TenLop  VARCHAR2(50 CHAR),
    Khoi    VARCHAR2(5 CHAR),
    GVCN    VARCHAR2(10 BYTE),
    CONSTRAINT PK_LOP PRIMARY KEY (MaLop),
    CONSTRAINT FK_LOP_GIAOVIEN FOREIGN KEY (GVCN) REFERENCES GIAOVIEN(MaGV)
);

--7. Bảng THOIKHOABIEU
CREATE TABLE THOIKHOABIEU (
    MaTKB       VARCHAR2(10 BYTE) NOT NULL,
    NgayLap     DATE,
    NgayApDung  DATE,
    Buoi        VARCHAR2(10 CHAR),
    NguoiTao    VARCHAR2(10 BYTE),
    MaHK        VARCHAR2(12 CHAR),
    CONSTRAINT PK_THOIKHOABIEU PRIMARY KEY (MaTKB),
    CONSTRAINT FK_THOIKHOABIEU_GIAOVIEN FOREIGN KEY (NguoiTao) REFERENCES GIAOVIEN(MaGV),
    CONSTRAINT FK_THOIKHOABIEU_HOCKY FOREIGN KEY (MaHK) REFERENCES HOCKY(MaHK)
);

--8. Bảng GIAOVIEN_CHUCVU
CREATE TABLE GIAOVIEN_CHUCVU (
    MaGV    VARCHAR2(10 BYTE),
    MaCV    VARCHAR2(10 BYTE),
    MaHK    VARCHAR2(12 CHAR),
    SoTiet  NUMBER,
    GhiChu  VARCHAR2(200 CHAR),
    CONSTRAINT PK_GIAOVIEN_CHUCVU PRIMARY KEY (MaGV, MaCV, MaHK),
    CONSTRAINT FK_GVCHUCVU_GIAOVIEN FOREIGN KEY (MaGV) REFERENCES GIAOVIEN(MaGV),
    CONSTRAINT FK_GVCHUCVU_CHUCVU FOREIGN KEY (MaCV) REFERENCES CHUCVU(MaCV),
    CONSTRAINT FK_GVCHUCVU_HOCKY FOREIGN KEY (MaHK) REFERENCES HOCKY(MaHK)
);

--9. Bảng HOC
CREATE TABLE HOC (
    MaLop           VARCHAR2(10 BYTE),
    MaMH            VARCHAR2(10 BYTE),
    MaHK            VARCHAR2(12 CHAR),
    HinhThuc        VARCHAR2(20 CHAR),
    PhanPhoiTiet    NUMBER,
    CONSTRAINT PK_HOC PRIMARY KEY (MaLop, MaMH, MaHK, HinhThuc),
    CONSTRAINT FK_HOC_LOP FOREIGN KEY (MaLop) REFERENCES LOP(MaLop),
    CONSTRAINT FK_HOC_MONHOC FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH),
    CONSTRAINT FK_HOC_HOCKY FOREIGN KEY (MaHK) REFERENCES HOCKY(MaHK)
);

--10. Bảng DAY
CREATE TABLE DAY (
    MaGV        VARCHAR2(10 BYTE),
    MaLop       VARCHAR2(10 BYTE),
    MaMH        VARCHAR2(10 BYTE),
    MaHK        VARCHAR2(12 CHAR),
    HinhThuc    VARCHAR2(20 CHAR),
    SoTiet      NUMBER,
    CONSTRAINT PK_DAY PRIMARY KEY (MaGV, MaLop, MaMH, MaHK, HinhThuc),
    CONSTRAINT FK_DAY_GIAOVIEN FOREIGN KEY (MaGV) REFERENCES GIAOVIEN(MaGV),
    CONSTRAINT FK_DAY_LOP FOREIGN KEY (MaLop) REFERENCES LOP(MaLop),
    CONSTRAINT FK_DAY_MONHOC FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH),
    CONSTRAINT FK_DAY_HOCKY FOREIGN KEY (MaHK) REFERENCES HOCKY(MaHK)
);

--11. Bảng CHITIETTKB
CREATE TABLE CHITIETTKB (
    MaTKB   VARCHAR2(10 BYTE),
    Thu     NUMBER,
    Tiet    NUMBER,
    MaLop   VARCHAR2(10 BYTE),
    MaGV    VARCHAR2(10 BYTE),
    MaMH    VARCHAR2(10 BYTE),
    CONSTRAINT PK_CHITIETTKB PRIMARY KEY (MaTKB, Thu, Tiet, MaLop, MaGV),
    CONSTRAINT FK_CHITIETTKB_THOIKHOABIEU FOREIGN KEY (MaTKB) REFERENCES THOIKHOABIEU(MaTKB),
    CONSTRAINT FK_CHITIETTKB_LOP FOREIGN KEY (MaLop) REFERENCES LOP(MaLop),
    CONSTRAINT FK_CHITIETTKB_GIAOVIEN FOREIGN KEY (MaGV) REFERENCES GIAOVIEN(MaGV),
    CONSTRAINT FK_CHITIETTKB_MONHOC FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH)
);

--12. Bảng YKIEN
CREATE TABLE YKIEN (
    MaYK        VARCHAR2(10 BYTE) NOT NULL,
    NoiDung     CLOB,
    NgayGui     DATE,
    AnDanh      NUMBER(1), -- 0: Không ẩn danh, 1: Ẩn danh
    MaGV        VARCHAR2(10 BYTE),
    CONSTRAINT PK_YKIEN PRIMARY KEY (MaYK),
    CONSTRAINT FK_YKIEN_GIAOVIEN FOREIGN KEY (MaGV) REFERENCES GIAOVIEN(MaGV)
);
