--Tạo user
CREATE USER TKB IDENTIFIED BY pass
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE TO TKB;
ALTER USER TKB QUOTA UNLIMITED ON USERS;

ALTER SESSION SET CURRENT_SCHEMA = TKB;

--Tạo bảng
-- 1. Bảng GIAOVIEN
CREATE TABLE GIAOVIEN (
    MaGV            VARCHAR2(10 BYTE) NOT NULL,
    HoGV            VARCHAR2(30 CHAR) NOT NULL,
    TenGV           VARCHAR2(15 CHAR) NOT NULL,
    GioiTinh        VARCHAR2(5 CHAR),
    ChuyenMon       VARCHAR2(200 CHAR),
    MaTCM           VARCHAR2(10 BYTE),
    SoTietQuyDinh   NUMBER,
    SoTietThucHien  NUMBER,
    SoTietDuThieu   NUMBER,
    Email           VARCHAR2(100 BYTE),
    SDT             VARCHAR2(15 BYTE),
    MatKhau         VARCHAR2(100 BYTE),
    GhiChu          VARCHAR2(200 CHAR),
    CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MaGV)
);

-- 2. Bảng CHUCVU
CREATE TABLE CHUCVU (
    MaCV    VARCHAR2(10 BYTE) NOT NULL,
    TenCV   VARCHAR2(100 CHAR),
    CONSTRAINT PK_CHUCVU PRIMARY KEY (MaCV)
);

-- 3. Bảng TOCHUYENMON
CREATE TABLE TOCHUYENMON (
    MaTCM       VARCHAR2(10 BYTE) NOT NULL,
    TenTCM      VARCHAR2(100 CHAR),
    ToTruong    VARCHAR2(10 BYTE),
    ToPho       VARCHAR2(10 BYTE),
    CONSTRAINT PK_TOCHUYENMON PRIMARY KEY (MaTCM),
    CONSTRAINT FK_TOCHUYENMON_ToTruong FOREIGN KEY (ToTruong) REFERENCES GIAOVIEN(MaGV),
    CONSTRAINT FK_TOCHUYENMON_ToPho FOREIGN KEY (ToPho) REFERENCES GIAOVIEN(MaGV)
);

-- 4. Bảng MONHOC
CREATE TABLE MONHOC (
    MaMH    VARCHAR2(10 BYTE) NOT NULL,
    TenMH   VARCHAR2(100 CHAR),
    Khoi    VARCHAR2(5 CHAR),
    MaTCM   VARCHAR2(10 BYTE),
    CONSTRAINT PK_MONHOC PRIMARY KEY (MaMH),
    CONSTRAINT FK_MONHOC_TOCHUYENMON FOREIGN KEY (MaTCM) REFERENCES TOCHUYENMON(MaTCM)
);

-- 5. Bảng LOP
CREATE TABLE LOP (
    MaLop   VARCHAR2(10 BYTE) NOT NULL,
    TenLop  VARCHAR2(50 CHAR),
    Khoi    VARCHAR2(5 CHAR),
    GVCN    VARCHAR2(10 BYTE),
    CONSTRAINT PK_LOP PRIMARY KEY (MaLop),
    CONSTRAINT FK_LOP_GIAOVIEN FOREIGN KEY (GVCN) REFERENCES GIAOVIEN(MaGV)
);

-- 6. Bảng THOIKHOABIEU
CREATE TABLE THOIKHOABIEU (
    MaTKB       VARCHAR2(10 BYTE) NOT NULL,
    NgayLap     DATE,
    NgayApDung  DATE,
    Buoi        VARCHAR2(10 CHAR),
    NguoiTao    VARCHAR2(10 BYTE),
    CONSTRAINT PK_THOIKHOABIEU PRIMARY KEY (MaTKB),
    CONSTRAINT FK_THOIKHOABIEU_GIAOVIEN FOREIGN KEY (NguoiTao) REFERENCES GIAOVIEN(MaGV)
);

-- 7. Bảng DAY (Phân công giảng dạy)
CREATE TABLE DAY (
    MaGV        VARCHAR2(10 BYTE),
    MaLop       VARCHAR2(10 BYTE),
    MaMH        VARCHAR2(10 BYTE),
    HinhThuc    VARCHAR2(20 CHAR),
    SoTiet      NUMBER,
    CONSTRAINT PK_DAY PRIMARY KEY (MaGV, MaLop, MaMH, HinhThuc),
    CONSTRAINT FK_DAY_GIAOVIEN FOREIGN KEY (MaGV) REFERENCES GIAOVIEN(MaGV),
    CONSTRAINT FK_DAY_LOP FOREIGN KEY (MaLop) REFERENCES LOP(MaLop),
    CONSTRAINT FK_DAY_MONHOC FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH)
);

-- 8. Bảng HOC (Môn học của lớp)
CREATE TABLE HOC (
    MaLop           VARCHAR2(10 BYTE),
    MaMH            VARCHAR2(10 BYTE),
    HinhThuc        VARCHAR2(20 CHAR),
    PhanPhoiTiet    NUMBER,
    CONSTRAINT PK_HOC PRIMARY KEY (MaLop, MaMH, HinhThuc),
    CONSTRAINT FK_HOC_LOP FOREIGN KEY (MaLop) REFERENCES LOP(MaLop),
    CONSTRAINT FK_HOC_MONHOC FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH)
);

-- 9. Bảng CHITIETTKB (Chi tiết thời khóa biểu)
CREATE TABLE CHITIETTKB (
    MaTKB   VARCHAR2(10 BYTE),
    Thu     NUMBER,
    Tiet    NUMBER,
    MaLop   VARCHAR2(10 BYTE),
    MaGV    VARCHAR2(10 BYTE),
    MaMH    VARCHAR2(10 BYTE),
    CONSTRAINT PK_CHITIETTKB PRIMARY KEY (MaTKB, Thu, Tiet, MaLop),
    CONSTRAINT FK_CHITIETTKB_THOIKHOABIEU FOREIGN KEY (MaTKB) REFERENCES THOIKHOABIEU(MaTKB),
    CONSTRAINT FK_CHITIETTKB_LOP FOREIGN KEY (MaLop) REFERENCES LOP(MaLop),
    CONSTRAINT FK_CHITIETTKB_GIAOVIEN FOREIGN KEY (MaGV) REFERENCES GIAOVIEN(MaGV),
    CONSTRAINT FK_CHITIETTKB_MONHOC FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH)
);

-- 10. Bảng GIAOVIEN_CHUCVU
CREATE TABLE GIAOVIEN_CHUCVU (
    MaGV    VARCHAR2(10 BYTE),
    MaCV    VARCHAR2(10 BYTE),
    SoTiet  NUMBER,
    GhiChu  VARCHAR2(200 CHAR),
    CONSTRAINT PK_GIAOVIEN_CHUCVU PRIMARY KEY (MaGV, MaCV),
    CONSTRAINT FK_GVCHUCVU_GIAOVIEN FOREIGN KEY (MaGV) REFERENCES GIAOVIEN(MaGV),
    CONSTRAINT FK_GVCHUCVU_CHUCVU FOREIGN KEY (MaCV) REFERENCES CHUCVU(MaCV)
);

-- 11. Bảng YKIEN
CREATE TABLE YKIEN (
    MaYK        VARCHAR2(10 BYTE) NOT NULL,
    NoiDung     CLOB,
    NgayGui     DATE,
    AnDanh      NUMBER(1), -- 0: Không ẩn danh, 1: Ẩn danh
    MaGV        VARCHAR2(10 BYTE), 
    CONSTRAINT PK_YKIEN PRIMARY KEY (MaYK),
    CONSTRAINT FK_YKIEN_GIAOVIEN FOREIGN KEY (MaGV) REFERENCES GIAOVIEN(MaGV)
);

--Cấp thêm quyền cho user
GRANT SELECT ON TKB.GIAOVIEN TO TKB;
GRANT INSERT ON TKB.GIAOVIEN TO TKB;
GRANT UPDATE ON TKB.GIAOVIEN TO TKB;
GRANT DELETE ON TKB.GIAOVIEN TO TKB;

GRANT SELECT ON TKB.CHUCVU TO TKB;
GRANT INSERT ON TKB.CHUCVU TO TKB;
GRANT UPDATE ON TKB.CHUCVU TO TKB;
GRANT DELETE ON TKB.CHUCVU TO TKB;

GRANT SELECT ON TKB.TOCHUYENMON TO TKB;
GRANT INSERT ON TKB.TOCHUYENMON TO TKB;
GRANT UPDATE ON TKB.TOCHUYENMON TO TKB;
GRANT DELETE ON TKB.TOCHUYENMON TO TKB;

GRANT SELECT ON TKB.MONHOC TO TKB;
GRANT INSERT ON TKB.MONHOC TO TKB;
GRANT UPDATE ON TKB.MONHOC TO TKB;
GRANT DELETE ON TKB.MONHOC TO TKB;

GRANT SELECT ON TKB.LOP TO TKB;
GRANT INSERT ON TKB.LOP TO TKB;
GRANT UPDATE ON TKB.LOP TO TKB;
GRANT DELETE ON TKB.LOP TO TKB;

GRANT SELECT ON TKB.THOIKHOABIEU TO TKB;
GRANT INSERT ON TKB.THOIKHOABIEU TO TKB;
GRANT UPDATE ON TKB.THOIKHOABIEU TO TKB;
GRANT DELETE ON TKB.THOIKHOABIEU TO TKB;

GRANT SELECT ON TKB.DAY TO TKB;
GRANT INSERT ON TKB.DAY TO TKB;
GRANT UPDATE ON TKB.DAY TO TKB;
GRANT DELETE ON TKB.DAY TO TKB;

GRANT SELECT ON TKB.HOC TO TKB;
GRANT INSERT ON TKB.HOC TO TKB;
GRANT UPDATE ON TKB.HOC TO TKB;
GRANT DELETE ON TKB.HOC TO TKB;

GRANT SELECT ON TKB.CHITIETTKB TO TKB;
GRANT INSERT ON TKB.CHITIETTKB TO TKB;
GRANT UPDATE ON TKB.CHITIETTKB TO TKB;
GRANT DELETE ON TKB.CHITIETTKB TO TKB;

GRANT SELECT ON TKB.GIAOVIEN_CHUCVU TO TKB;
GRANT INSERT ON TKB.GIAOVIEN_CHUCVU TO TKB;
GRANT UPDATE ON TKB.GIAOVIEN_CHUCVU TO TKB;
GRANT DELETE ON TKB.GIAOVIEN_CHUCVU TO TKB;

GRANT SELECT ON TKB.YKIEN TO TKB;
GRANT INSERT ON TKB.YKIEN TO TKB;
GRANT UPDATE ON TKB.YKIEN TO TKB;
GRANT DELETE ON TKB.YKIEN TO TKB;

--Thêm bộ dữ liệu Quản trị viên
INSERT INTO TKB.GIAOVIEN (
    MaGV,
    HoGV,
    TenGV,
    GioiTinh,
    ChuyenMon,
    MaTCM,
    SoTietQuyDinh,
    SoTietThucHien,
    SoTietDuThieu,
    Email,
    SDT,
    MatKhau,
    GhiChu
) VALUES (
    'ADMIN',
    'Quản trị',
    'viên',
    'Khác',
    'Quản trị hệ thống',
    'QTHT',
    0,
    0,
    0,
    'admin@example.com',
    '0000000000',
    'pass',
    'Tài khoản quản trị viên cao nhất của hệ thống.'
);
